version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
  build:
    commands:
      - find ${CODEBUILD_SRC_DIR_BuildArtifact}
      - ./node_modules/.bin/sls deploy -v -p ${CODEBUILD_SRC_DIR_BuildArtifact}/.serverless
