version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
  build:
    commands:
      - ./node_modules/.bin/sls package
      - |
        sed -i 's/"artifact": "[^"]*.serverless/"artifact": ".serverless/' .serverless/serverless-state.json
artifacts:
  files:
    - '.serverless/**/*'
